services:
  grafana:
    image: grafana/grafana:13.0-slim
    network_mode: host
    # ports:
    #   - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro

volumes:
  grafana_data:
